# 0.CoLab Basic Keys
## 0.1. 셀 관련 단축키
- 아래로: Ctrl+m+b
- 위로 : Ctrl+m+a

## 0.2. 에디터 모드=> 마크다운 모두
- Ctrl + m + m (m 꾹 누르기)
- 되돌리기 : Ctrl + m + y

## 0.3. 셀 실행
- 현재 셀을 실행하고 다음셀로 커서 이동: shift + enter
- 현재 셀을 실행(하고 커서를 현재 셀로 그대로) : ctrl + enter

## 0.4. 셀 삭제
- Ctrl + m + d

# 1.머신러닝(Machine Learning) 주요 개념 파헤치기
## 1.1.머신러닝 개념 정리
- 머신러닝이란 Bounded Rational 이라는 인간의 불완전성을 해결하기위해 Robert Simon과 친구들이 만든 machine을 Perfect Rational을 가기위한  더 효율적 작동하기 위해서 학습을 시키는 방법을 말한다. 파블로브의 개, 스키너의 쥐 와같은 학습법을 통해서 machine을 좀 더 Rational 에 다가갈 수 있게 만드는 기법이다.


- 기계학습: 기계가 스스로 학습하여 데이터의 규칙(또는 패턴) 을 찾고, 새로운 데이터에 대해서 해당 규칙을 통해 예측하고 분류하는 기술(결정할 수 있게 하는 기술)
- 무슨 문제를 해결하기 위한 규칙 설계를 기계가 스스로 하는 기법


## 1.2.이 인물들은 어떤 사람일까? 머신러닝과 연관된 사람은 누구일까? 
- 귀도 반 로섬 => python 창시자
- 프랭크 로제블라트 => 인공지능과 딥러닝 연구의 선구자
- Alan Turing앨런 튜링 => 이미테이션게임 주인공 
  - 1950_Alan Turing_Computing Machinery and Intelligence 논문: 기계도 생각할 수 있을까?  
  - 1959_Arthur Samuel_Some Studies in Machine Learning Using the Game of Checkers  => Machine Learning Define

## 1.3.개인활동. 머신러닝은 딥러닝, 인공지능(AI) 단어가 자주 함께 등장한다! 머신러닝은 어떤 개념의 하위 분야이고, 어떤 개념의 상위분야인가? 이들의 관계를 확인해보자. 
- Artificial Inteligence > Machine Learning > Deep Learning
- Machine Learning은 Deep Learning등의 상위 개념이다.   

## 1.4.머신러닝 이전에는 어떤 방식으로 동작을 자동화 했을까?
### 1.4.1. Herbert A. Simon은 제한된 합리성(Bounded Rationality) 문제를 해결하기 위해 **Carnegie Mellon University에서 인공지능 연구소(Artificial Intelligence Laboratory)**를 설립했습니다.[1][2]

### 1.4.2.  핵심 조직 설립

Simon은 Allen Newell과 함께 **Carnegie Mellon University의 인공지능 연구소**를 설립하여 제한된 합리성 문제에 대한 해결책을 모색했습니다. 이 연구소에서 그들은 인간의 문제 해결 과정을 컴퓨터로 시뮬레이션하는 연구를 진행했습니다.[2][1]

### 1.4.3.  구체적 성과와 프로그램

1956년, Simon과 Newell, J.C. Shaw는 **Logic Theorist**라는 최초의 인공지능 프로그램을 개발했습니다. 이는 인간의 사고 과정을 모방하여 논리적 문제를 해결할 수 있는 "thinking machine"이었습니다.[3][1][2]

이어서 1957년에는 **General Problem Solver(GPS)**를 개발하여 휴리스틱 기법과 수단-목적 분석을 통해 다양한 문제를 해결하는 시스템을 구축했습니다.[4][1]

### 1.4.4.  조직적 확장

Simon은 Carnegie Mellon에서 제한된 합리성 연구를 위한 학제간 접근을 위해 여러 학과와 기관을 설립하거나 확장하는 데 중요한 역할을 했습니다:[2]

- **컴퓨터 과학과** (1965년 설립)
- **심리학과** 창설/확장
- **사회 및 의사결정 과학과** 창설
- **철학과** 확장
- **비즈니스 스쿨** (현재의 Tepper School of Business) 설립

### 1.4.5.  이론적 기여

Simon은 제한된 합리성을 해결하기 위한 핵심 개념으로 **"satisficing"**(만족화) 전략을 제시했습니다. 이는 최적해를 찾기보다는 충분히 만족할 만한 해를 찾는 것으로, 인간의 인지적 한계 내에서 합리적 의사결정을 하는 방법입니다.[5][6][7]

Simon과 Newell의 이러한 연구는 1975년 **ACM 튜링상** 수상으로 인정받았으며, Simon은 1978년 **노벨경제학상**을 수상했습니다. 이들이 설립한 조직과 개발한 이론은 현재까지도 인공지능과 인지과학 분야의 기초가 되고 있습니다.[8][1][4][2]

[1] https://en.wikipedia.org/wiki/Allen_Newell
[2] https://www.cmu.edu/50/founder-stories/story-simon.html
[3] https://www.historyofinformation.com/detail.php?id=742
[4] https://www.britannica.com/biography/Allen-Newell
[5] https://en.wikipedia.org/wiki/Bounded_rationality
[6] https://plato.stanford.edu/entries/bounded-rationality/
[7] https://lmscontent.embanet.com/USC/PPD555/Readings/BryanJones_BoundedRationalityandPublicPolicyHerbertASimonandtheDecisionalFoundationofCollectiveChoice.pdf
[8] https://ai.cmu.edu/research-and-policy-impact/history-of-ai-at-cmu
[9] https://www.jstor.org/stable/2634943
[10] http://innovbfa.viabloga.com/files/Herbert_Simon___theories_of_bounded_rationality___1972.pdf
[11] https://link.springer.com/article/10.1007/s10203-024-00436-2
[12] https://onlinelibrary.wiley.com/doi/10.1111/puar.13540
[13] https://blog.othor.ai/herbert-simon-and-bounded-rationality-the-human-reality-behind-decision-intelligence-6ba392ae2499
[14] https://thedecisionlab.com/biases/bounded-rationality
[15] https://www.scielo.br/j/rep/a/CWfwPPVWKvLrndfxR9vYFHL
[16] https://en.wikipedia.org/wiki/Herbert_A._Simon
[17] https://www.letr.ai/en/blog/story-20211126-3
[18] https://www.library.cmu.edu/about/news/2023-07/herb-simon-allen-newell-ai-cmu
[19] https://central.yourtext.guru/at-the-heart-of-artificial-intelligence-evolution-herbert-a-simons-visionary-legacy/
[20] http://www.aistudy.co.kr/pioneer/Simon.H.A.htm
[21] https://www.cmu.edu/simon/what-is-simon/history.html
[22] https://www.simoninstitute.ch/blog/post/how-computers-will-continue-to-shape-the-world-herbert-a-simon-video-transcript/
[23] https://www.youtube.com/watch?v=r-naBUbhUEs
[24] https://history.computer.org/pioneers/simon.html
[25] https://scienceon.kisti.re.kr/srch/selectPORSrchArticle.do?cn=NART24013292
[26] https://thedecisionlab.com/thinkers/computer-science/herbert-simon



- 1.4.6.강사의 정답:  Rule-Based expert System(규칙 기반 전문가 시스템)
- 1.4.7.한계?
  - 복잡한 상황에 취약함 => 예외가 많거나, 패턴이 모호한 상황에서는 규칙으로 처리가 불가능
  - 규칙이 너무 많아짐 => 수천개의 조건을 지정하는데 어려움이 있음
  - 변화에 적응 못함 => 새로운 상황이 나타나면 사람이 다시 코드를 설계


## 1.5.머신러닝은 규칙기반시스템과 뭐가 다를까?
- 머신러닝은 규칙을 사람이 직접 정의하지 않고, 데이터로 부터 학습해서 스스로 기계가 규칙을 만들어냄
- 예를 들어, 어떤 이메일이 스팸인지 아닌지를 사람이 직접 판단하지 않고, 데이터에서 패턴(규칙)을 찾아내게 함 

## 1.6.머신러닝 활용 사례
- 이미지/음성 인식
- 추천 시스템(넷플릭스, 유튜브)
- 금융 사기 탐지
- 고객 이탈 여부 탐지
- 꽃의 품종을 분류하는 사례
- 자율 중행 차량


## 1.7.머신러닝 주요 구성요소 (용어 정리)
- 데이터(Data):
  - 학습의 가반이 되는 자료.
  - 입력(input)과 정답(Label) 또는 출력(Output)으로 구성됨.
  - 양질의 데이터가 모델의 성능에 결정적인 역할을 함.

- 기계 == 모델(Model):
  - 데이터를 기반으로 학습된 알고리즘(수학적/통계적) 구조. 
  - 입력 데이터를 받아 결과를 출력하는 함수 역할

- 학습(Training): 파블로브의 개, 스키너의 쥐 실험을 통해서 보상시스템이 학습곡선을 향상시킨다는 결과를 가져왔다. 따라서 기계도 동일 Logic을 통해서 학습시킨다.
  - 데이터의 규칙(pattern)을 찾아내는 과정.
  - 예측의 오류(오차)를 최소화하는 방향으로 학습함.

- 예측(Prediction): Statistic Analysis를 통해서 Standard Deviation Table을 만들어 내고, 오차범위(신뢰수준 95%)를 기준으로 Data만 만족해로 사용한다. 
  - 학습된 모델을 사용해 새로운 데이터에 적용하여 결과를 도출하는 과정

- 평가(Evaluation): Null Hypothesis와 Alterative Hypothesis를 통해서 측정값이 얼마나 정확한지를 평가한다.
  - 모델의 예측 성능을 평가하는 과정

## 1.8.머신러닝의 종류(학습 유형에 따른 구분)
- Supervised Learning
  - 입력(특성데이터)과 정답(Label)
  - 특성 데이터 : 문제 데이터,특성(Feature), **독립변수**:independent variable(컬럼,열), X(대문자; 값이 많아서)
  - 답 데이터 : 정답 데이터, 레이블(Label, 라벨),**종속변수**:dependent variable,y(크기가작아서 소문자로) 
---
- UnSupervised Learning
  - 확률통계 값으로 나타난다. 여기서는 안한다.
---
- Reinforcement Learning
  - 1897_Ivan Petrovich **Pavlov**_Pavlov's Dogs
  - 1933_Burrhus Frederic **Skinner**_Resistance to extinction in the process of conditioning
  - 여기서는 안한다.

# 2.머신러닝 프로젝트 진행 순서(Workflow)
- Classify(분류)//Regression(회귀)
- Classify(Decision Making Tree// Ensemble(앙상블)//Bagging()// Gradient Boosting Machine(GBM)) 
- 문제정의> Data 수집>Data 전처리> Data 탐색> 모델 선택> 모델 학습> 모델예측 및 평가> 모델 활용 

## 2.1.문제정의
  - 어떤 문제를 해결할 것인가?
  - 예: 이메일이 스팸인지 아닌지 분류하기
  - 어떤 데이터가 필요할까?
  - 어떤 도구를 사용할까?

## 2.2.데이터 수집
  - 내부 데이터베이스, 센서, 웹크롤링, OPEN API, 공공데이터등 문제에 맞는 데이터 확보
  - 데이터 양이 많이 있으면 유리, 데이터의 질도 중요함


## 2.3.데이터 전처리(PreProcessing)
  - Missing Vlaue(결측값) 처리(삭제, 채우기)
      - MCAR (Missing Completely At Random): 완전무작위결측
      - MAR (Missing At Random): 무작위결측
      - MNAR (Missing Not At Random): 비무작위결측
  - Outlier(이상치) 제거
      - Statistical Outlier: 통계적 이상값 (표준편차 기준)
      - Extreme Value: 극값
      - Anomalous Data Point: 이상 데이터 포인트
  - 범주형 변수(컬럼) 처리(범주 -> 수치: 인코딩)
  - 정규화/표준화 (스케일링 단위맞추기)
  - 텍스트나 이미지 등은 특수 전처리가 필요
  - 데이터 분할(문제,답 // 학습용데이터//예측용데이터(테스트용))
    - 학습용과 테스트용을 분리하는 비율
    - 7:3 or 8:2 정답은 없다

## 2.4.데이터 탐색(EDA: Exploratory Data Analysis)
  - 기술 통계량
  - 집계: 빈도수 체크, 중앙값, 평균값, 사분위 수 등
  - 변수(열, 컬럼)간의 상관관계(Correlation of Coefficient)

## 2.5.모델 선택(Hyper Parabeter 선택)
  - 문제에 적합한 유형의 모델을 선택

## 2.6.모델 학습
  - 학습용 데이터를 활용하여 학습 진행
  - fit() : 맞추다, 모델이 데이터에 맞춰서 학습한다는 의미

## 2.7.모델 예측 및 평가
  - 새로운 데이터를 사용해 성능 측정하고 예측 결과를 확인
  - 사용 측정 지표
    - 정확도, 정밀도, 재현율, F1 Score
    - MSE, RMSE, R_Squared 점수 등


## 2.8.모델 활용
  - 서비스 배포
  - 주기적 점검
  - 보고서 결과로 활용

---    
- 위 순서대로 진행되는 1차적인 순서지만, 모델의 성능을 높이기 위해서 다시 모델 선택 및 하이퍼 파라미터조정
- 데이터 전처리 및 수집등으로 다시 단계를 옮겨 진행하기도 함

# 3.모델의 성능을 이해하고 정리하는 주요 개념
- 과대적합(Over-fitting): 편차가 Over_Value_Bias
  - 모델의 규칙이 너무 복잡해진 상태
  - **훈련**데이터의 **성능**은 높지만 새로운 데이터를 예측했을 때 성능이 떨어지는 상태

- 과소적합(Under-fitting): 편차가 Under_Value_Bias
  - 모델의 규칙이 너무 단순해진 상태
  - **훈련**데이터와 **테스트**데이터 모두 예측 성능이 떨어지는 상태

- 일반화(unbias): 편이가 없다 unbias 
  - 일반적으로 모델의 성능이 높고 보편화됨(좋은 모델)

- 교차검증(Cross Validation): 
  - 모델의 일반화 성능을 확인하기 위해서 여러번 테스트 데이터를 만들고 점수를 확인하는 방법

# 4.정리
## 4.1.Supervised Learning에서 Supervised란 무엇을 의미하는지, 지도학습 내에서 상세 유형을 찾아보기
- Supervised란? 
  - 독립변수(X) => Question(특성;Feature Data) => input 
  - 종속변수(y) => Answer(레이블;Label Data)=> output 
  - 특성 데이터(X - 독립변수)

        차원성: 보통 m×n 행렬 형태 (m: 샘플 수, n: 특성 수)

        역할: 예측을 위한 입력 정보로, 결과에 영향을 미치는 요인들

        표기법: 대문자 X를 사용하는 이유는 일반적으로 다차원 행렬이기 때문

        예시:

        주택 가격 예측: 면적, 방 개수, 위치, 건축연도 등

        신용평가: 소득, 직업, 신용기록, 부채비율 등

  - 레이블 데이터(y - 종속변수)

        차원성: 보통 m×1 벡터 형태 (m: 샘플 수)

        역할: 모델이 예측해야 할 목표값

        표기법: 소문자 y를 사용하는 이유는 상대적으로 단순한 구조이기 때문

        특징: 독립변수들의 함수로 표현됨 (y = f(X))
  
  - Classify
  - Regression

## 4.2.Machine Learning에서 E-mail 스팸 분류, 가격 예측이 서로 다른점?

| 유형                                 | 설명                    | 예시               |
| ---------------------------------- | --------------------- | ---------------- |
| **지도 학습 (Supervised Learning)**    | 입력과 정답(Label)을 이용해 학습 | 이메일 스팸 분류, 가격 예측 |
| **비지도 학습 (Unsupervised Learning)** | 정답 없이 입력만으로 구조 파악     | 고객 세분화, 이상 탐지    |
| **강화 학습 (Reinforcement Learning)** | 보상 기반으로 최적의 행동 학습     | 게임 플레이, 로봇 제어    |

# 5.실습
## 5.1.Working_Flow목표: 머신러닝 흐름 이해하기(Workflow)
- 문제정의
- AND 연산 결과를 출력하는 모델을 만들어보자.
- KNN(K-Nearest Neighbors) 알고리즘 적용하기

In [1]:
# 환경세팅

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 머신러닝 패키지(도구): aklearn
from sklearn.neighbors import KNeighborsClassifier

## 5.2.데이터 수집(정리)
- X data : X1, X2 => training row0~7, test row8~10
- y data : AND

- AND 연산
 
| 문제 X1 | 문제 X2 | 답 (AND) |
|---------|---------|------------|
|   0 |   0 |   0 |
|   0 |   1 |   0 |
|   1 |   0 |   0 |
|   1 |   1 |   1 |

In [2]:
# Dataset
and_data = pd.DataFrame({'X1':[0,0,1,1,1,1,1,1,0,1],
                         'X2':[0,1,0,1,1,1,0,1,1,1],
                         'AND':[0,0,0,1,1,1,0,1,0,1]})
and_data

# 특성(Feature => X1, X2 //  Label => AND )

   X1  X2  AND
0   0   0    0
1   0   1    0
2   1   0    0
3   1   1    1
4   1   1    1
5   1   1    1
6   1   0    0
7   1   1    1
8   0   1    0
9   1   1    1

## 5.3.PreProcess of Data 데이터 전처리
- 문제(X), 답(y) 변수에 각각 분리해서 담아주기
- train, test용으로 행을 분리하기(일반적으로 7:3)

In [3]:
and_data.shape # 0~6 (7개): training, 7~9(3개): test

(10, 3)

In [4]:
# # 위치 기반 - 행 접근( loc, iloc 개념 사용하기)
# # loc - 눈에 보이는 라벨값 위치 접근 location
# display(df.loc[0]) # 1차원
# display(df.loc[1:]) # 1에서부터 마지막 행 데이터까지 접근

# # 위치 기반 - 열 접근(인덱싱1)
# # loc, iloc 없이 []열린상태에서 인덱싱을 실행 => 컬럼 접근 명령(규칙)
# display(df['이름']) # 1차원
# display(df[['이름']]) # 2차원 - []를 한번 더 이중으로 씌우면 2차원으로 출력(df)
# display(df[['이름', '성별']])

# # 위치 기반 - 열 접근 (loc, iloc 개념 사용하기)
# print('--loc, 라벨 이름 위치 기반--')
# display(df.loc[:,"이름"])
# display(df.loc[:,["이름"]])
# display(df.loc[:,["이름","성별"]]) # 열의 이름을 여러개로 설정 => [] 묶어줌 (열의 위치 명확히)
# display(df.loc[:,"이름":"성별"]) # 성별 컬럼 포함해서 데이터 접근
# print('--iloc, 인덱스 위치 기반--')
# display(df.iloc[:,0]) # 열인덱스 번호가 보이지 않지만, 존재함!
# display(df.iloc[:,[0]]) # 0번째 열에 접근하지만, 2차원으로 표현할래!
# display(df.iloc[:,[0,2]]) # 인덱싱 기법으로 입력할 때 []씌워서 여러개 입력
# display(df.iloc[:,0:2]) # 슬라이싱 기법으로 입력할 때 []씌우지 않음 # loc랑 차이 비교

# # 위치기반 - 행, 열 동시 접근
# # df2.loc
# df.iloc[0:2,0]

In [5]:
# X변수에 X1, X2 담기
X = and_data.iloc[:,0:2]
# y변수에 AND 담기
y = and_data.iloc[:,2]

# 크기확인
print(X.shape)
print(y.shape)

(10, 2)
(10,)

In [6]:
# training, test분리(행) 7:3의 비율로 나눠라
# X는 X1,X2 Column 구분 => 독립변수=> Feature // training용 문제 7개, 테스트용 문제 3개
X_train = X.iloc[0:7]
X_test = X.iloc[7:10]

# y는 And Column으로 구분 => 종속변수 => Label // training용 답 7개, 테스트용 답 3개
y_train = y.iloc[0:7]
y_test = y.iloc[7:10]

print("훈련용")
print(X_train.shape, y_train.shape)
print("테스트용")
print(X_test.shape, y_test.shape)


# 훈련용 문제가 7개이면, 답도 7개여야 한다.
# 훈련용 특성개수 2개이면, 테스트 특성 개수도 2개여야한다.

훈련용
(7, 2) (7,)
테스트용
(3, 2) (3,)

In [7]:
and_data

   X1  X2  AND
0   0   0    0
1   0   1    0
2   1   0    0
3   1   1    1
4   1   1    1
5   1   1    1
6   1   0    0
7   1   1    1
8   0   1    0
9   1   1    1

## 5.4.Search of Data데이터 탐색

In [8]:
# 학습의 사용되는 데이터 가장 중요함! >> 모델읭 일반화에 영향을 줌!
# X_train,
# y_train
# y_train 안에 어떤 값이 가장 많이 들어있을까?
X_train.head(3)

# 수치형 데이터 -> 머신러닝 충분히 학습 가능!
y_train.head(3)

y_train.value_counts()
# 4개 : 3개 -> 데이터의 양은 많지 않아도 찾아야할 라벨 카테고리는 다른 균등하게 들어있음
# 분류 형태 문제 해결
# - Class(카테고리, 범주) Label
# - 수치로 표현되어져 있지만, 0과 1사이에 크고 작음의 의미가 없음

AND
0    4
1    3
Name: count, dtype: int64


## 5.5.Select of Model 모델 선택(및 하이퍼 파라미터 조정)
- HyperParameter의 궁극적 목적: Bias와 Variance의 균형을 맞추는것 : 편향-분산 균형(Bias-Variance Tradeoff)
    - 편향(Bias): 모델의 예측과 실제 값의 차이
    - 분산(Variance): 새로운 데이터에 대한 모델의 민감도
- 하이퍼 파리미터: 사람이 설정하는 파라미터 값 -> 모델마다 다름
- 모델 선택: 분류 문제를 잘 해결 할 모델 선택


- CF) Parameters vs Hyperparameters: 본질적 차이점
- Parameters (매개변수)
    - 학습 과정에서 자동으로 도출되는 내부 변수
    - 데이터로부터 자동으로 학습되고 업데이트됨
    - 예: 선형회귀의 가중치, 신경망의 연결 강도

- Hyperparameters (하이퍼파라미터)
    - 학습 시작 전에 수동으로 설정하는 외부 구성 변수
    - 모델의 학습 과정 자체를 제어
    - 예: 학습률, 배치 크기, 신경망 층 수

- 이러한 구분은 **"하이퍼(Hyper)"**라는 접두사가 붙는 이유를 설명합니다 - 일반 매개변수보다 상위 수준에서 학습 과정을 통제하기 때문입니다.

In [9]:
# KNN 모델 생성
# 이웃의 수(K-neighbors == n_neighbors)가 하이퍼 파라미터
knn = KNeighborsClassifier(n_neighbors=1) #최적 1
# 이웃 1개만 확인해서 예측하는 설정

## 5.6.Learning 모델 학습
- fit(): 데이터에 맞춰서 학습, 데이터연결
- 훈련용: X_train, y_train

In [10]:
# 모델명.fit(훈련문제, 훈련답)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

## 5.7.Espect&Evaluation모델 예측 및 평가

In [11]:
# test 활용 예측
# X_test, y_test

# 예측을 진행하면서, 답을 알려주는 예측이 있는가?
# 문제를 출제
# 모델명.predict(테스트문제)
pred = knn.predict(X_test)
print("-입력:")
display(X_test)
print("-예측 결과:", pred)
print("-실제값:")
display(y_test)

-입력:

   X1  X2
7   1   1
8   0   1
9   1   1

-예측 결과: [1 0 1]
-실제값:

7    1
8    0
9    1
Name: AND, dtype: int64

In [12]:
# 정확도 지표 성능확인
from sklearn.metrics import accuracy_score
# accuracy_score(실제값, 예측값)
accuracy_score(y_test,pred) # 1.0 => 100% (백분율) 맞춘 상황

1.0

In [13]:
# 실제 0.1
# 예측 0,1
# 조합을 표로 정리해놓은 기능 -> 혼동행렬표(cunfusion_matrix)
from sklearn.metrics import confusion_matrix
cf = confusion_matrix(y_test, pred)

cf_df = pd.DataFrame(cf, index = ["실제0", "실제1"],
                     columns = ["예측0", "예측1"])

cf_df

# accurancy 결과를 해석할 수 있는 행렬표
# 실제 0인 것을 예측 0이라고 잘 맞춤 : 1개
# 실제 1인 것을 예측 1이라고 잘 맞춤 : 2개
# accuracy 3/3 = 1.0 100% 맞춘 상황!

     예측0  예측1
실제0    1    0
실제1    0    2